### ISSUE TITLE
用户名有emoji的人无法封禁

### ISSUE THREAD

**Issue by qwq233** [chajianku/wmzz_ban#3]
RT
![pic.png](https://i.loli.net/2020/03/09/kUfxRDyedr4INFT.png)

**Comment by chajianku** [comment]
这个应该不是百度账号原始ID，是贴吧单独的昵称吧
点开他个人主页看看地址栏main?un=后面应该有原始ID

**Comment by qwq233** [comment]
似乎没有 这是此人主页链接
> http://tieba.baidu.com/home/main?un=&ie=utf-8&id=tb.1.79a480f2.v2QUkKqgcOkhOm9kZPf4Iw&fr=pb&red_tag=m1839336616

**Comment by chajianku** [comment]
点击私信后发现他的真实ID应该是**4564954016**

**Comment by qwq233** [comment]
哦哦谢谢了！www
